name: Build Universal macOS Binary

on:
  push:
    branches:
      - automation
  pull_request:

jobs:
  build-universal-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install x86_64 Homebrew (if missing)
        run: |
          if [[ ! -d "/usr/local/Homebrew" ]]; then
            echo "Installing Homebrew for x86_64..."
            arch -x86_64 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
          else
            echo "x86_64 Homebrew already installed."
          fi

      - name: Install Dependencies
        run: |
          # Install essential tools (native)
          brew update
          brew install cmake ninja llvm

          # Install Boost separately for each architecture
          echo "Installing Boost for arm64..."
          brew install boost

          echo "Installing Boost for x86_64..."
          arch -x86_64 /usr/local/bin/brew install boost

      - name: Configure Build
        run: |
          mkdir -p build
          pushd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja" \
                   -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                   -DBOOST_ROOT=$(brew --prefix boost)
          popd

      - name: Build Project
        run: |
          pushd build
          cmake --build .
          popd

      - name: Prepare Universal Binary
        run: |
          mkdir -p artifacts

          # Merge arm64 and x86_64 binaries (if built separately)
          lipo -create -output artifacts/universal_binary \
            build/bin/shinysocks_arm64 \
            build/bin/shinysocks_x86_64

      - name: Verify Universal Binary
        run: |
          file artifacts/universal_binary

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-build
          path: artifacts/*
          retention-days: 1
