name: Build Universal macOS Binary

on:
  push:
    branches:
      - automation
  pull_request:

jobs:
  build-universal-macos:
    runs-on: macos-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install Dependencies
        run: |
          # Install essential tools
          brew update
          brew install cmake ninja llvm

          # Install Boost for both architectures
          if [[ $(uname -m) == "arm64" ]]; then
            echo "Installing Boost for Universal Build"
            arch -x86_64 /opt/homebrew/bin/brew install boost
            brew install boost
          else
            brew install boost
          fi

      - name: Configure Build
        run: |
          mkdir -p build
          pushd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja" \
                   -DCMAKE_OSX_ARCHITECTURES="x86_64;arm64" \
                   -DBOOST_ROOT=$(brew --prefix boost)
          popd

      - name: Build Project
        run: |
          pushd build
          cmake --build .
          popd

      - name: Prepare Universal Binary
        run: |
          mkdir -p artifacts

          # Merge arm64 and x86_64 binaries (if built separately)
          lipo -create -output artifacts/universal_binary \
            build/bin/shinysocks_arm64 \
            build/bin/shinysocks_x86_64

      - name: Verify Universal Binary
        run: |
          file artifacts/universal_binary

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: macos-universal-build
          path: artifacts/*
          retention-days: 1
