name: Build Universal C++ Application with Boost

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: macos-latest


    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Build Tools
        run: |
            brew update
            brew install cmake ninja llvm

      - name: Download boost
        run: |
          curl -s -L https://archives.boost.io/release/1.87.0/source/boost_1_87_0.tar.bz2 -o boost.tar.bz2
          tar -xjf boost.tar.bz2

      - name: Build and install Boost for both architectures
        run: |
          cd boost_1_87_0
          ./bootstrap.sh
          ./b2 address-model=64 architecture=arm+x86 link=static threading=multi runtime-link=static --with-system --with-program_options --with-serialization --with-context --with-coroutine
          sudo ./b2 install

      - name: Configure Build
        run: |
          mkdir -p build
          pushd build
          cmake .. -DCMAKE_BUILD_TYPE=Release -G "Ninja" \
                   -DCMAKE_OSX_ARCHITECTURES="x86_64"
          popd

      - name: Build Project
        run: |
          pushd build
          cmake --build .
          popd

      - name: Prepare Universal Binary
        run: |
          ls -la  build/bin/
          mkdir -p artifacts
          lipo -create -output artifacts/universal_binary \
            build/bin/your_binary_arm64 \
            build/bin/your_binary_x86_64

      - name: Archive Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: universal-macos-build
          path: artifacts/*
          retention-days: 1
